### PR TITLE
feat: added open graph

### PR DESCRIPTION
**Pull request by Nakamcode**
Added open graph to increase the click-through rate when the website link is shared

### CODE REVIEW

**Review by Arman-ali-khan-786 — COMMENTED** [review]
can you elaborate more on how it works and benefits and all of it

**Comment by Nakamcode** [comment]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/
### This will be the preview image when the link is shared on social media such as twitter,facebook,discord & whatsapp

Group 2

**Comment by Arman-ali-khan-786** [comment]
> ### An open graph is a preview image that shows when a link is shared on social media
> _for more info about open graphs read the blog below_ https://ahrefs.com/blog/open-graph-meta-tags/
> 
> ### This will be the preview image when the link is shared on social media such as twitter,facebook,discord & whatsapp
> Group 2

okay great i didnot knew about this thanks for the info btw

**Review by Arman-ali-khan-786 — APPROVED** [review]

**Comment by Nakamcode** [comment]
thanks

**Pull request merged**
